'use client'

import { useEffect, useState } from 'react'

type Package = { id: string; title: string; slug: string }
type Availability = { id: string; safari_package_id: string; available_from: string; available_to: string; departure_time: string | null; capacity: number; booked_spaces: number; status: string; notes: string | null; safari_packages?: { title: string; slug: string } | null }
const blank = { safari_package_id: '', available_from: '', available_to: '', departure_time: '', capacity: 12, notes: '', status: 'available' }

export function AdminAvailabilityManager() {
  const [packages, setPackages] = useState<Package[]>([])
  const [rows, setRows] = useState<Availability[]>([])
  const [form, setForm] = useState(blank)
  const [status, setStatus] = useState('')
  const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); const [availabilityResponse, packageResponse] = await Promise.all([fetch('/api/admin/availability'), fetch('/api/admin/safaris')]); const availability = await availabilityResponse.json(); const packagesJson = await packageResponse.json(); if (!availabilityResponse.ok) setStatus(availability.error ?? 'Unable to load availability.'); else setRows(availability.data ?? []); setPackages(packagesJson.data ?? []); setLoading(false) }
  useEffect(() => { void load() }, [])
  const update = (key: keyof typeof blank, value: string | number) => setForm((current) => ({ ...current, [key]: value }))
  const save = async (event: React.FormEvent) => { event.preventDefault(); setStatus('Saving…'); const response = await fetch('/api/admin/availability', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const json = await response.json(); if (!response.ok) return setStatus(json.error ?? 'Unable to save availability.'); setStatus('Availability added.'); setForm({ ...blank, safari_package_id: form.safari_package_id }); await load() }
  const remove = async (id: string) => { const response = await fetch(`/api/admin/availability?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); const json = await response.json(); setStatus(response.ok ? 'Availability removed.' : json.error ?? 'Unable to remove availability.'); if (response.ok) await load() }
  return <section className="availability-manager dashboard-section"><div className="package-manager-heading"><div><p className="eyebrow">Availability</p><h2>Open safari dates</h2></div></div>{status && <p className="package-manager-status" role="status">{status}</p>}<form className="availability-form" onSubmit={save}><label>Safari package<select required value={form.safari_package_id} onChange={(event) => update('safari_package_id', event.target.value)}><option value="">Choose a package</option>{packages.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Available from<input required type="date" value={form.available_from} onChange={(event) => update('available_from', event.target.value)} /></label><label>Available to<input required type="date" value={form.available_to} onChange={(event) => update('available_to', event.target.value)} /></label><label>Departure time<input type="time" value={form.departure_time} onChange={(event) => update('departure_time', event.target.value)} /></label><label>Capacity<input required type="number" min="1" value={form.capacity} onChange={(event) => update('capacity', Number(event.target.value))} /></label><label>Notes<input value={form.notes} onChange={(event) => update('notes', event.target.value)} placeholder="Seasonal departure details" /></label><button className="button button-dark" type="submit">Add dates <span>→</span></button></form><div className="availability-list">{loading ? <p className="dashboard-muted">Loading availability…</p> : rows.length === 0 ? <p className="dashboard-muted">No dates configured yet.</p> : rows.map((row) => <div className="availability-row" key={row.id}><div><strong>{row.safari_packages?.title ?? 'Safari package'}</strong><span>{row.available_from} to {row.available_to}{row.departure_time ? ` · Departs ${row.departure_time.slice(0, 5)}` : ''}</span></div><div><span>{row.booked_spaces} / {row.capacity} booked</span><span className={row.status === 'unavailable' ? 'availability-unavailable' : 'availability-open'}>{row.status}</span></div><button className="text-link" type="button" onClick={() => void remove(row.id)} disabled={row.booked_spaces > 0}>Remove</button></div>)}</div></section>
}
