'use client'

import { useEffect, useState } from 'react'

type PackageRow = { id: string; slug: string; title: string; tag: string | null; meta: string | null; description: string | null; starting_price: number | null; duration_days: number | null; published: boolean }
const blank: Partial<PackageRow> = { slug: '', title: '', tag: 'Signature', meta: '', description: '', starting_price: 4200, duration_days: 8, published: false }

export function AdminPackageManager() {
  const [packages, setPackages] = useState<PackageRow[]>([])
  const [form, setForm] = useState<Partial<PackageRow>>(blank)
  const [editing, setEditing] = useState<string | null>(null)
  const [status, setStatus] = useState('')
  const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); const response = await fetch('/api/admin/safaris'); const json = await response.json(); if (!response.ok) setStatus(json.error ?? 'Unable to load packages.'); else setPackages(json.data ?? []); setLoading(false) }
  useEffect(() => { void load() }, [])
  const update = (key: keyof PackageRow, value: string | number | boolean) => setForm((current) => ({ ...current, [key]: value }))
  const save = async (event: React.FormEvent) => { event.preventDefault(); setStatus('Saving…'); const response = await fetch('/api/admin/safaris', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing ? { ...form, id: editing } : form) }); const json = await response.json(); if (!response.ok) return setStatus(json.error ?? 'Unable to save package.'); setStatus('Saved.'); setEditing(null); setForm(blank); await load() }
  const archive = async (item: PackageRow) => { const response = await fetch('/api/admin/safaris', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: item.id, title: item.title, published: false }) }); if (!response.ok) { const json = await response.json(); setStatus(json.error ?? 'Unable to archive package.'); } else { setStatus('Package archived.'); await load() } }
  return <section className="package-manager dashboard-section"><div className="package-manager-heading"><div><p className="eyebrow">Catalog</p><h2>Safari packages</h2></div><button className="button button-dark" type="button" onClick={() => { setEditing(null); setForm(blank); setStatus('') }}>New package <span>+</span></button></div>{status && <p className="package-manager-status" role="status">{status}</p>}<form className="package-form" onSubmit={save}><div><label>Slug<input required value={form.slug ?? ''} disabled={Boolean(editing)} onChange={(event) => update('slug', event.target.value)} placeholder="great-migration" /></label><label>Title<input required value={form.title ?? ''} onChange={(event) => update('title', event.target.value)} placeholder="The Great Migration" /></label></div><div><label>Short description<textarea value={form.description ?? ''} onChange={(event) => update('description', event.target.value)} rows={3} /></label><div className="package-form-grid"><label>Price<input type="number" min="0" value={form.starting_price ?? ''} onChange={(event) => update('starting_price', Number(event.target.value))} /></label><label>Days<input type="number" min="1" value={form.duration_days ?? ''} onChange={(event) => update('duration_days', Number(event.target.value))} /></label></div></div><label className="package-publish"><input type="checkbox" checked={Boolean(form.published)} onChange={(event) => update('published', event.target.checked)} /> Publish on site</label><div className="package-form-actions"><button className="button button-dark" type="submit">{editing ? 'Update package' : 'Create package'} <span>→</span></button>{editing && <button className="button button-quiet" type="button" onClick={() => { setEditing(null); setForm(blank) }}>Cancel</button>}</div></form><div className="package-list">{loading ? <p className="dashboard-muted">Loading catalog…</p> : packages.length === 0 ? <p className="dashboard-muted">No packages yet. Create the first one above.</p> : packages.map((item) => <article className="package-row" key={item.id}><div><span className={item.published ? 'package-status is-published' : 'package-status'}>{item.published ? 'Published' : 'Draft'}</span><h3>{item.title}</h3><p>{item.slug} · {item.duration_days ?? '—'} days · ${(item.starting_price ?? 0).toLocaleString()}</p></div><div className="package-row-actions"><button type="button" className="text-link" onClick={() => { setEditing(item.id); setForm(item); setStatus('') }}>Edit</button>{item.published && <button type="button" className="text-link" onClick={() => void archive(item)}>Archive</button>}</div></article>)}</div></section>
}
