export type SafariPackage = {
  slug: string
  title: string
  meta: string
  description: string
  image: string
  tag: string
  location: string
  duration: string
  startingPrice: string
  bestTime: string
  travelStyle: string
  highlights: string[]
  itinerary: { day: string; title: string; description: string }[]
  included: string[]
  excluded: string[]
  accommodation: string
  transport: string
  wildlife: string[]
  gallery: { src: string; alt: string }[]
  faq: { question: string; answer: string }[]
}

export const safariPackages: SafariPackage[] = [
  { slug: 'great-migration', title: 'The Great Migration', meta: '8 days · Masai Mara', description: 'Track the herds across the Mara, with time to watch, listen, and let the day unfold.', image: '/images/elephants-savannah.jpg', tag: 'Signature', location: 'Masai Mara, Kenya', duration: '8 days / 7 nights', startingPrice: 'From $4,200 per guest', bestTime: 'July – October', travelStyle: 'Private, unhurried safari', highlights: ['Private 4x4 game drives', 'Mara conservancy time', 'Expert local guiding', 'Small-camp atmosphere'], itinerary: [{ day: 'Day 01', title: 'Arrive in Nairobi', description: 'Settle in at a quiet city base before your journey west begins.' }, { day: 'Day 02', title: 'Into the Mara', description: 'Fly or drive into the Mara and ease into the landscape with an afternoon game drive.' }, { day: 'Days 03–06', title: 'Following the herds', description: 'Spend your days with your guide, moving at the pace of the wildlife and the light.' }, { day: 'Day 07', title: 'A final morning', description: 'One more dawn drive, followed by time to reflect on the season’s great movement.' }, { day: 'Day 08', title: 'Return journey', description: 'Travel back to Nairobi with the option to continue to the coast.' }], included: ['Private safari vehicle and guide', 'Accommodation as outlined in the itinerary', 'All scheduled game drives', 'Park and conservancy fees'], excluded: ['International flights', 'Travel insurance', 'Personal purchases and gratuities'], accommodation: 'A considered mix of intimate tented camps and lodges selected for their setting, guiding, and sense of place.', transport: 'Private 4x4 safari vehicle with a dedicated local guide. Air transfers can be discussed during planning.', wildlife: ['Wildebeest', 'Lion', 'Elephant', 'Cheetah', 'Giraffe'], gallery: [{ src: '/images/safari-vehicle-rear.jpg', alt: 'Acacia tree at sunset in Kenya' }, { src: '/images/elephant-viewing.jpg', alt: 'Elephants on the Kenyan plains' }, { src: '/images/field-training.jpg', alt: 'Golden light over a safari landscape' }], faq: [{ question: 'Is this itinerary fixed?', answer: 'No. It is a thoughtful starting point. We shape the final route around your dates, interests, and preferred pace.' }, { question: 'Can we add the coast?', answer: 'Yes. An Indian Ocean extension can be discussed with your safari designer.' }] },
  { slug: 'northern-wilds', title: 'Northern Wilds', meta: '10 days · Samburu & Laikipia', description: 'Head north for red earth, open country, and close encounters with Kenya’s rare wildlife.', image: '/images/safari-drive.jpg', tag: 'Off the map', location: 'Samburu & Laikipia, Kenya', duration: '10 days / 9 nights', startingPrice: 'From $4,200 per guest', bestTime: 'June – October', travelStyle: 'Private, conservation-led safari', highlights: ['Northern Kenya landscapes', 'Community conservancy visits', 'Rare northern species', 'Space for slow travel'], itinerary: [{ day: 'Days 01–02', title: 'Welcome to Laikipia', description: 'Begin among open ranchland and learn how conservation and community work together.' }, { day: 'Days 03–07', title: 'Into Samburu', description: 'Explore the dry-country landscape with long, flexible days in the field.' }, { day: 'Days 08–09', title: 'A quieter rhythm', description: 'Take time for walking, conversation, and the details that game drives can miss.' }, { day: 'Day 10', title: 'Return journey', description: 'Make your way back with a final look at northern Kenya.' }], included: ['Private safari vehicle and guide', 'Accommodation as outlined in the itinerary', 'Scheduled activities and fees', 'Selected community experiences'], excluded: ['International flights', 'Travel insurance', 'Personal purchases and gratuities'], accommodation: 'Small camps and lodges chosen for their low-key character, local connection, and access to the landscape.', transport: 'Private 4x4 vehicle throughout, with internal air connections considered where they make the route more comfortable.', wildlife: ['Reticulated giraffe', 'Grevy’s zebra', 'Oryx', 'Elephant', 'Leopard'], gallery: [{ src: '/images/safari-vehicle-rear.jpg', alt: 'Northern Kenya landscape' }, { src: '/images/elephants-savannah.jpg', alt: 'Wildlife in open country' }, { src: '/images/elephant-viewing.jpg', alt: 'Elephants in the field' }], faq: [{ question: 'What makes the north different?', answer: 'Northern Kenya has a drier, more spacious character and a strong connection between conservation, communities, and wildlife.' }, { question: 'Is it suitable for first-time safari travellers?', answer: 'Yes. The route can be paced gently, with your guide adapting each day to your interests.' }] },
  { slug: 'family-safari', title: 'The Family Safari', meta: '7 days · Amboseli & Tsavo', description: 'A relaxed route through Amboseli and Tsavo, planned around curious young travellers and unhurried days.', image: '/images/giraffe-encounter.jpg', tag: 'For families', location: 'Amboseli & Tsavo, Kenya', duration: '7 days / 6 nights', startingPrice: 'From $4,200 per guest', bestTime: 'June – October', travelStyle: 'Private family safari', highlights: ['Flexible daily rhythm', 'Big elephant country', 'Family-friendly camps', 'Learning through discovery'], itinerary: [{ day: 'Day 01', title: 'Arrive and settle in', description: 'Meet your team and ease into the journey at a comfortable base.' }, { day: 'Days 02–03', title: 'Amboseli mornings', description: 'Enjoy early drives, open skies, and time to learn about the park’s elephants.' }, { day: 'Days 04–06', title: 'The Tsavo story', description: 'Move east for a different landscape, with wildlife days shaped around your family.' }, { day: 'Day 07', title: 'A gentle farewell', description: 'Take one final look at the landscape before your onward journey.' }], included: ['Private safari vehicle and guide', 'Accommodation as outlined in the itinerary', 'Scheduled game drives', 'Family-focused planning support'], excluded: ['International flights', 'Travel insurance', 'Personal purchases and gratuities'], accommodation: 'Comfortable camps and lodges with room to rest between drives and a welcoming approach to families.', transport: 'Private 4x4 vehicle, with the daily rhythm adapted around ages, interests, and energy levels.', wildlife: ['Elephant', 'Lion', 'Giraffe', 'Zebra', 'Hippo'], gallery: [{ src: '/images/elephant-viewing.jpg', alt: 'Elephants crossing the plains' }, { src: '/images/field-training.jpg', alt: 'Kenyan safari country' }, { src: '/images/safari-vehicle-rear.jpg', alt: 'Sunset over Amboseli' }], faq: [{ question: 'Can the days be shortened?', answer: 'Absolutely. Your guide can adapt the pace, timing, and length of drives around your family.' }, { question: 'Can we combine this with the coast?', answer: 'Yes. Ask your safari designer about adding time by the Indian Ocean.' }] },
]

export const safariBySlug = (slug: string) => safariPackages.find((safari) => safari.slug === slug)
export const safariSlugs = safariPackages.map((safari) => safari.slug)
export const itineraryCards = safariPackages.map(({ slug, title, meta, description, image, tag }) => ({ slug, title, meta, description, image, tag }))
